// Generated by CoffeeScript 1.6.3
(function() {
  var SlideLoop;

  SlideLoop = (function() {
    function SlideLoop(el) {
      var s, _i, _len, _ref;
      this.el = el;
      this.current = 0;
      this.count = this.el.getElementsByClassName('slide').length;
      console.log(this.count);
      this.timer = null;
      this.el.getElementsByClassName('slider-container')[0].style.width = (this.count * 100) + "%";
      _ref = this.el.getElementsByClassName('slide');
      for (_i = 0, _len = _ref.length; _i < _len; _i++) {
        s = _ref[_i];
        s.style.width = (100 / this.count) + "%";
      }
    }

    SlideLoop.prototype.getSlide = function(id) {
      return this.el.getElementsByClassName('slide')[this.current];
    };

    SlideLoop.prototype.goTo = function(id) {
      var pos;
      pos = id * -100;
      return this.el.getElementsByClassName('slider-container')[0].style.left = pos + "%";
    };

    SlideLoop.prototype.next = function() {
      this.current++;
      this.current = this.current % this.count;
      this.goTo(this.current);
      return this.stop();
    };

    SlideLoop.prototype.prev = function() {
      if (this.current <= 0) {
        return;
      }
      return this.goTo(this.current--);
    };

    SlideLoop.prototype.start = function(t) {
      var _this = this;
      return this.timer = setInterval(function() {
        _this.current++;
        _this.current = _this.current % _this.count;
        return _this.goTo(_this.current);
      }, t);
    };

    SlideLoop.prototype.stop = function() {
      if (this.timer) {
        return clearInterval(this.timer);
      }
    };

    return SlideLoop;

  })();

  module.exports = SlideLoop;

}).call(this);
